versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.06.26.07.40:
    folder: all
  1.90.0-a.m+25.06.26.07.40:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.06.26.07.40:
    folder: all
  1.91.0-a.m+25.06.26.07.40:
    folder: all
