versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.04.28.13.47:
    folder: all
  1.90.0-a.d+25.10.26.16.35:
    folder: all
  1.90.0-a.d+25.11.13.14.29:
    folder: all
  1.90.0-a.m+25.04.28.13.47:
    folder: all
