versions:
  1.90.0-a.d+25.10.21.17.19:
    folder: all
  1.90.0-a.d+25.10.22.19.26:
    folder: all
  1.90.0-a.d+25.10.23.21.21:
    folder: all
  1.90.0-a.d+25.10.27.14.10:
    folder: all
  1.90.0-a.d+25.10.28.14.11:
    folder: all
  1.90.0-a.d+25.10.29.10.44:
    folder: all
  1.90.0-a.d+25.10.31.13.50:
    folder: all
  1.90.0-a.m+25.10.22.17.16:
    folder: all
  1.90.0-a.m+25.10.28.14.11:
    folder: all
  1.90.0-a.m+25.10.29.10.44:
    folder: all
  1.90.0-a.m+25.10.31.13.50:
    folder: all
