versions:
  1.90.0-a.d+25.10.21.17.19:
    folder: all
  1.90.0-a.d+25.10.22.19.26:
    folder: all
  1.90.0-a.d+25.10.23.21.21:
    folder: all
  1.90.0-a.d+25.10.27.14.10:
    folder: all
  1.90.0-a.d+25.10.28.14.11:
    folder: all
  1.90.0-a.d+25.10.29.10.44:
    folder: all
  1.90.0-a.d+25.10.30.11.13:
    folder: all
  1.90.0-a.d+25.10.31.13.50:
    folder: all
  1.90.0-a.d+25.11.01.13.26:
    folder: all
  1.90.0-a.d+25.11.02.09.54:
    folder: all
  1.90.0-a.d+25.11.15.16.24:
    folder: all
  1.90.0-a.d+25.11.23.13.03:
    folder: all
  1.90.0-a.d+25.11.24.20.46:
    folder: all
  1.90.0-a.m+25.10.22.17.16:
    folder: all
  1.90.0-a.m+25.10.28.14.11:
    folder: all
  1.90.0-a.m+25.10.29.10.44:
    folder: all
  1.90.0-a.m+25.10.31.13.50:
    folder: all
  1.90.0-a.m+25.11.01.13.26:
    folder: all
  1.90.0-a.m+25.11.02.09.54:
    folder: all
  1.90.0-a.m+25.11.15.16.24:
    folder: all
  1.90.0-a.m+25.11.23.13.03:
    folder: all
  1.90.0-a.m+25.11.24.20.46:
    folder: all
  1.90.0-b.1:
    folder: all
