versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.09.06.12.17:
    folder: all
  1.90.0-a.m+24.12.20.14.29:
    folder: all
  1.90.0-a.m+25.09.06.12.17:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.09.06.12.17:
    folder: all
  1.91.0-a.m+25.09.06.12.17:
    folder: all
