versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+24.11.05.14.58:
    folder: all
  1.90.0-a.d+25.12.02.08.31:
    folder: all
  1.90.0-a.d+25.12.02.11.08:
    folder: all
  1.90.0-a.d+25.12.02.13.07:
    folder: all
  1.90.0-a.m+24.11.05.14.59:
    folder: all
  1.90.0-b.1:
    folder: all
