versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.22.22.37:
    folder: all
  1.90.0-a.d+25.10.25.15.33:
    folder: all
  1.90.0-a.m+25.07.02.11.53:
    folder: all
