versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.03.21.17.00:
    folder: all
  1.90.0-a.d+25.10.18.22.44:
    folder: all
  1.90.0-a.d+25.10.19.12.15:
    folder: all
  1.90.0-a.d+25.10.19.13.59:
    folder: all
  1.90.0-a.m+25.03.21.17.00:
    folder: all
  1.90.0-a.m+25.10.19.02.52:
    folder: all
  1.90.0-a.m+25.10.19.13.59:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.19.13.59:
    folder: all
  1.91.0-a.m+25.10.19.13.59:
    folder: all
