versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.01.27.23.01:
    folder: all
  1.90.0-a.d+25.11.05.21.22:
    folder: all
  1.90.0-a.m+25.01.27.23.01:
    folder: all
