versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.09.24.16.35:
    folder: all
  1.90.0-a.d+25.10.29.21.21:
    folder: all
  1.90.0-a.m+25.05.25.16.34:
    folder: all
  1.90.0-a.m+25.10.29.21.21:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.29.21.21:
    folder: all
  1.91.0-a.d+25.12.27.17.25:
    folder: all
  1.91.0-a.m+25.10.29.21.21:
    folder: all
