versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.25.19.05:
    folder: all
  1.90.0-a.d+25.11.14.03.49:
    folder: all
  1.90.0-a.m+25.08.25.19.05:
    folder: all
  1.90.0-a.m+25.11.14.03.49:
    folder: all
  1.90.0-b.1:
    folder: all
