versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.05.00.08:
    folder: all
  1.90.0-a.d+25.10.11.12.45:
    folder: all
  1.90.0-a.d+25.10.20.13.13:
    folder: all
  1.90.0-a.d+25.11.03.00.13:
    folder: all
  1.90.0-a.d+25.11.04.09.10:
    folder: all
  1.90.0-a.d+25.11.05.08.17:
    folder: all
  1.90.0-a.d+25.11.07.23.51:
    folder: all
  1.90.0-a.d+25.11.10.23.51:
    folder: all
  1.90.0-a.d+25.11.11.23.19:
    folder: all
  1.90.0-a.d+25.11.12.23.07:
    folder: all
  1.90.0-a.d+25.11.13.23.33:
    folder: all
  1.90.0-a.d+25.11.22.00.03:
    folder: all
  1.90.0-a.d+25.11.23.00.44:
    folder: all
  1.90.0-a.d+25.11.25.22.37:
    folder: all
  1.90.0-a.d+25.11.30.23.56:
    folder: all
  1.90.0-a.d+25.12.06.11.33:
    folder: all
  1.90.0-a.d+25.12.06.22.59:
    folder: all
  1.90.0-a.d+25.12.10.15.22:
    folder: all
  1.90.0-a.m+25.09.05.00.08:
    folder: all
  1.90.0-a.m+25.10.11.12.45:
    folder: all
  1.90.0-a.m+25.10.20.13.13:
    folder: all
  1.90.0-a.m+25.11.04.09.10:
    folder: all
  1.90.0-a.m+25.11.13.23.33:
    folder: all
  1.90.0-b.1:
    folder: all
