versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.05.00.08:
    folder: all
  1.90.0-a.d+25.10.11.12.45:
    folder: all
  1.90.0-a.d+25.10.20.13.13:
    folder: all
  1.90.0-a.d+25.11.03.00.13:
    folder: all
  1.90.0-a.d+25.11.04.09.10:
    folder: all
  1.90.0-a.m+25.09.05.00.08:
    folder: all
  1.90.0-a.m+25.10.11.12.45:
    folder: all
  1.90.0-a.m+25.10.20.13.13:
    folder: all
  1.90.0-a.m+25.11.04.09.10:
    folder: all
