versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.11.11.25:
    folder: all
  1.90.0-a.d+25.09.29.14.17:
    folder: all
  1.90.0-a.d+25.10.22.13.44:
    folder: all
  1.90.0-a.d+25.10.30.10.35:
    folder: all
  1.90.0-a.m+25.07.02.13.50:
    folder: all
  1.90.0-a.m+25.09.11.11.25:
    folder: all
