versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.18.19.58:
    folder: all
  1.90.0-a.d+25.10.23.17.54:
    folder: all
  1.90.0-a.d+25.10.27.11.02:
    folder: all
  1.90.0-a.d+25.10.28.09.31:
    folder: all
  1.90.0-a.m+25.07.08.19.56:
    folder: all
  1.90.0-a.m+25.10.22.17.25:
    folder: all
