versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.06.25.18.43:
    folder: all
  1.90.0-a.m+21.09.14.23.10:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.06.25.18.43:
    folder: all
  1.91.0-a.m+21.09.14.23.10:
    folder: all
