versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.08.26.12.02:
    folder: all
  1.90.0-a.d+25.10.24.20.06:
    folder: all
  1.90.0-a.m+25.08.26.12.02:
    folder: all
  1.90.0-a.m+25.10.24.20.06:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.24.20.06:
    folder: all
  1.91.0-a.d+25.12.24.20.19:
    folder: all
  1.91.0-a.m+25.10.24.20.06:
    folder: all
