versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.05.02.11.24:
    folder: all
  1.90.0-a.m+21.06.08.00.11:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.05.02.11.24:
    folder: all
  1.91.0-a.m+21.06.08.00.11:
    folder: all
