versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.23.23.03:
    folder: all
  1.90.0-a.d+25.10.18.12.24:
    folder: all
  1.90.0-a.d+25.11.02.22.45:
    folder: all
  1.90.0-a.d+25.11.03.21.51:
    folder: all
  1.90.0-a.d+25.11.05.08.17:
    folder: all
  1.90.0-a.d+25.11.07.23.51:
    folder: all
  1.90.0-a.d+25.11.09.21.32:
    folder: all
  1.90.0-a.d+25.11.11.23.00:
    folder: all
  1.90.0-a.d+25.11.30.22.52:
    folder: all
  1.90.0-a.d+25.12.06.11.31:
    folder: all
  1.90.0-a.d+25.12.06.22.59:
    folder: all
  1.90.0-a.d+25.12.10.14.28:
    folder: all
  1.90.0-a.d+25.12.11.15.02:
    folder: all
  1.90.0-a.m+25.08.23.23.03:
    folder: all
  1.90.0-a.m+25.10.18.12.24:
    folder: all
  1.90.0-a.m+25.11.03.21.51:
    folder: all
  1.90.0-b.1:
    folder: all
