versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.12.22.13:
    folder: all
  1.90.0-a.d+25.10.27.20.34:
    folder: all
  1.90.0-a.d+25.10.31.09.24:
    folder: all
  1.90.0-a.d+25.11.06.21.14:
    folder: all
  1.90.0-a.m+25.09.12.22.39:
    folder: all
  1.90.0-a.m+25.11.02.14.33:
    folder: all
  1.90.0-b.1:
    folder: all
