versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.09.16.01:
    folder: all
  1.90.0-a.d+25.10.29.08.37:
    folder: all
  1.90.0-a.d+25.12.15.15.12:
    folder: all
  1.90.0-a.m+25.10.09.16.06:
    folder: all
  1.90.0-a.m+25.12.15.19.00:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.15.15.12:
    folder: all
  1.91.0-a.d+25.12.21.22.26:
    folder: all
  1.91.0-a.d+25.12.23.11.49:
    folder: all
  1.91.0-a.d+26.01.04.15.57:
    folder: all
  1.91.0-a.m+25.12.15.19.00:
    folder: all
  1.91.0-a.m+25.12.23.11.49:
    folder: all
