versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.08.00.43:
    folder: all
  1.90.0-a.d+25.10.27.09.07:
    folder: all
  1.90.0-a.d+25.10.27.23.55:
    folder: all
  1.90.0-a.d+25.10.29.00.12:
    folder: all
  1.90.0-a.m+25.10.01.22.19:
    folder: all
  1.90.0-a.m+25.10.08.00.43:
    folder: all
  1.90.0-a.m+25.10.27.09.07:
    folder: all
