versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.08.00.43:
    folder: all
  1.90.0-a.d+25.10.27.09.07:
    folder: all
  1.90.0-a.d+25.10.27.23.55:
    folder: all
  1.90.0-a.d+25.10.29.00.12:
    folder: all
  1.90.0-a.d+25.11.01.10.05:
    folder: all
  1.90.0-a.d+25.11.01.22.12:
    folder: all
  1.90.0-a.d+25.11.03.00.12:
    folder: all
  1.90.0-a.d+25.11.03.23.55:
    folder: all
  1.90.0-a.d+25.11.05.00.24:
    folder: all
  1.90.0-a.d+25.11.05.22.31:
    folder: all
  1.90.0-a.d+25.11.06.23.59:
    folder: all
  1.90.0-a.d+25.11.07.23.51:
    folder: all
  1.90.0-a.d+25.11.09.21.16:
    folder: all
  1.90.0-a.m+25.10.01.22.19:
    folder: all
  1.90.0-a.m+25.10.08.00.43:
    folder: all
  1.90.0-a.m+25.10.27.09.07:
    folder: all
  1.90.0-a.m+25.11.01.22.12:
    folder: all
  1.90.0-a.m+25.11.03.23.55:
    folder: all
