versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.13.18.43:
    folder: all
  1.90.0-a.d+25.10.31.17.30:
    folder: all
  1.90.0-a.d+25.11.15.16.39:
    folder: all
  1.90.0-a.m+25.07.27.17.50:
    folder: all
  1.90.0-a.m+25.10.31.17.30:
    folder: all
