versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+24.12.12.19.39:
    folder: all
  1.90.0-a.d+25.11.14.21.06:
    folder: all
  1.90.0-a.d+25.11.15.22.13:
    folder: all
  1.90.0-a.m+24.12.12.19.39:
    folder: all
  1.90.0-a.m+25.11.15.22.13:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.11.15.22.13:
    folder: all
  1.91.0-a.m+25.11.15.22.13:
    folder: all
