versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.14.14.26:
    folder: all
  1.90.0-a.m+25.10.14.14.26:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.14.14.26:
    folder: all
  1.91.0-a.d+25.12.21.21.03:
    folder: all
  1.91.0-a.d+25.12.23.19.48:
    folder: all
  1.91.0-a.d+25.12.25.15.18:
    folder: all
  1.91.0-a.d+26.01.05.16.02:
    folder: all
  1.91.0-a.d+26.01.05.18.53:
    folder: all
  1.91.0-a.d+26.01.05.20.27:
    folder: all
  1.91.0-a.d+26.01.06.16.32:
    folder: all
  1.91.0-a.d+26.01.07.20.49:
    folder: all
  1.91.0-a.m+25.10.14.14.26:
    folder: all
  1.91.0-a.m+25.12.21.21.03:
    folder: all
  1.91.0-a.m+25.12.29.13.08:
    folder: all
