versions:
  1.90.0:
    folder: all
  1.90.0-a.d+25.12.19.05.38:
    folder: all
  1.90.0-a.m+25.12.18.17.38:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.19.05.38:
    folder: all
  1.91.0-a.d+25.12.19.10.39:
    folder: all
  1.91.0-a.d+25.12.20.00.15:
    folder: all
  1.91.0-a.d+25.12.21.06.43:
    folder: all
  1.91.0-a.d+25.12.22.11.05:
    folder: all
  1.91.0-a.d+25.12.23.10.45:
    folder: all
  1.91.0-a.d+25.12.24.04.47:
    folder: all
  1.91.0-a.d+25.12.25.05.07:
    folder: all
  1.91.0-a.d+25.12.26.10.05:
    folder: all
  1.91.0-a.d+26.01.05.15.39:
    folder: all
  1.91.0-a.d+26.01.05.17.07:
    folder: all
  1.91.0-a.d+26.01.06.00.48:
    folder: all
  1.91.0-a.m+25.12.18.17.38:
    folder: all
  1.91.0-a.m+25.12.22.10.07:
    folder: all
  1.91.0-a.m+25.12.23.10.04:
    folder: all
  1.91.0-a.m+25.12.23.23.05:
    folder: all
  1.91.0-a.m+25.12.24.19.33:
    folder: all
  1.91.0-a.m+25.12.25.18.32:
    folder: all
  1.91.0-a.m+26.01.04.08.40:
    folder: all
