versions:
  1.90.0:
    folder: all
  1.90.0-a.d+25.12.19.05.38:
    folder: all
  1.90.0-a.m+25.12.18.17.38:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.19.05.38:
    folder: all
  1.91.0-a.d+25.12.19.10.39:
    folder: all
  1.91.0-a.d+25.12.20.00.15:
    folder: all
  1.91.0-a.d+25.12.21.06.43:
    folder: all
  1.91.0-a.d+25.12.22.11.05:
    folder: all
  1.91.0-a.d+25.12.23.10.45:
    folder: all
  1.91.0-a.m+25.12.18.17.38:
    folder: all
  1.91.0-a.m+25.12.22.10.07:
    folder: all
  1.91.0-a.m+25.12.23.10.04:
    folder: all
