versions:
  1.90.0:
    folder: all
  1.90.0-a.d+25.12.19.05.38:
    folder: all
  1.90.0-a.m+25.12.18.17.38:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.19.05.38:
    folder: all
  1.91.0-a.d+25.12.19.10.39:
    folder: all
  1.91.0-a.m+25.12.18.17.38:
    folder: all
