versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.25.23.15:
    folder: all
  1.90.0-a.d+25.11.03.21.51:
    folder: all
  1.90.0-a.d+25.11.05.08.17:
    folder: all
  1.90.0-a.d+25.11.07.23.52:
    folder: all
  1.90.0-a.d+25.11.11.22.59:
    folder: all
  1.90.0-a.m+25.08.25.23.15:
    folder: all
  1.90.0-a.m+25.11.03.21.51:
    folder: all
  1.90.0-b.1:
    folder: all
