versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.05.18.48:
    folder: all
  1.90.0-a.d+25.11.01.19.45:
    folder: all
  1.90.0-a.d+25.11.03.18.54:
    folder: all
  1.90.0-a.d+25.11.18.11.26:
    folder: all
  1.90.0-a.m+25.09.05.18.48:
    folder: all
  1.90.0-a.m+25.11.01.17.57:
    folder: all
  1.90.0-a.m+25.11.03.18.54:
    folder: all
  1.90.0-b.1:
    folder: all
