versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.18.19.54:
    folder: all
  1.90.0-a.d+25.10.20.17.25:
    folder: all
  1.90.0-a.d+25.10.25.15.52:
    folder: all
  1.90.0-a.m+25.09.04.13.21:
    folder: all
  1.90.0-a.m+25.10.22.17.24:
    folder: all
