versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.09.07.01.20:
    folder: all
  1.90.0-a.d+25.10.06.11.11:
    folder: all
  1.90.0-a.d+25.10.17.17.51:
    folder: all
  1.90.0-a.d+25.10.23.00.26:
    folder: all
  1.90.0-a.m+25.07.18.17.31:
    folder: all
  1.90.0-a.m+25.10.06.11.11:
    folder: all
  1.90.0-a.m+25.10.23.00.26:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.23.00.26:
    folder: all
  1.91.0-a.d+26.01.02.09.19:
    folder: all
  1.91.0-a.m+25.10.23.00.26:
    folder: all
