versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.15.01.40:
    folder: all
  1.90.0-a.d+25.10.20.10.01:
    folder: all
  1.90.0-a.m+25.09.30.20.11:
    folder: all
  1.90.0-a.m+25.10.20.10.01:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.20.10.01:
    folder: all
  1.91.0-a.m+25.10.20.10.01:
    folder: all
