versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.09.09.12.01:
    folder: all
  1.90.0-a.d+25.10.29.19.44:
    folder: all
  1.90.0-a.d+25.12.11.22.15:
    folder: all
  1.90.0-a.m+25.09.09.12.01:
    folder: all
  1.90.0-a.m+25.10.29.19.44:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.11.22.15:
    folder: all
  1.91.0-a.d+25.12.23.11.51:
    folder: all
  1.91.0-a.d+25.12.24.20.08:
    folder: all
  1.91.0-a.d+26.01.04.11.21:
    folder: all
  1.91.0-a.m+25.10.29.19.44:
    folder: all
  1.91.0-a.m+25.12.11.22.15:
    folder: all
  1.91.0-a.m+25.12.26.20.37:
    folder: all
