versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.18.20.25:
    folder: all
  1.90.0-a.d+25.10.20.17.33:
    folder: all
  1.90.0-a.d+25.10.21.13.55:
    folder: all
  1.90.0-a.d+25.10.27.14.33:
    folder: all
  1.90.0-a.d+25.10.29.20.51:
    folder: all
  1.90.0-a.d+25.11.06.10.27:
    folder: all
  1.90.0-a.m+25.07.28.14.02:
    folder: all
  1.90.0-a.m+25.09.18.20.25:
    folder: all
  1.90.0-a.m+25.10.20.17.33:
    folder: all
  1.90.0-a.m+25.10.29.20.51:
    folder: all
