versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.07.02.19.12:
    folder: all
  1.90.0-a.d+25.10.19.21.04:
    folder: all
  1.90.0-a.d+25.10.29.15.44:
    folder: all
  1.90.0-a.d+25.11.02.20.08:
    folder: all
  1.90.0-a.d+25.12.01.03.03:
    folder: all
  1.90.0-a.d+25.12.03.19.33:
    folder: all
  1.90.0-a.d+25.12.15.21.52:
    folder: all
  1.90.0-a.m+25.07.02.19.12:
    folder: all
  1.90.0-a.m+25.10.19.21.04:
    folder: all
  1.90.0-a.m+25.10.29.15.44:
    folder: all
  1.90.0-a.m+25.11.02.20.08:
    folder: all
  1.90.0-b.1:
    folder: all
