versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.04.21.15.19:
    folder: all
  1.90.0-a.m+25.07.04.20.38:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.04.21.15.19:
    folder: all
  1.91.0-a.m+25.07.04.20.38:
    folder: all
