versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.13.17.09:
    folder: all
  1.90.0-a.d+25.12.02.14.52:
    folder: all
  1.90.0-a.m+25.04.17.17.55:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.02.14.52:
    folder: all
  1.91.0-a.m+25.04.17.17.55:
    folder: all
