versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.25.17.26:
    folder: all
  1.90.0-a.d+25.10.08.13.15:
    folder: all
  1.90.0-a.d+25.12.02.12.47:
    folder: all
  1.90.0-a.m+25.08.01.18.48:
    folder: all
  1.90.0-a.m+25.10.29.15.17:
    folder: all
  1.90.0-a.m+25.12.02.17.10:
    folder: all
  1.90.0-b.1:
    folder: all
