versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+24.12.13.03.05:
    folder: all
  1.90.0-a.m+24.12.13.03.05:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+24.12.13.03.05:
    folder: all
  1.91.0-a.d+26.01.03.18.00:
    folder: all
  1.91.0-a.m+24.12.13.03.05:
    folder: all
  1.91.0-a.m+26.01.03.18.00:
    folder: all
