versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.16.11.30:
    folder: all
  1.90.0-a.d+25.10.25.02.23:
    folder: all
  1.90.0-a.d+25.10.26.02.22:
    folder: all
  1.90.0-a.d+25.10.29.17.15:
    folder: all
  1.90.0-a.m+25.08.16.11.30:
    folder: all
  1.90.0-a.m+25.10.25.15.30:
    folder: all
  1.90.0-a.m+25.10.26.02.22:
    folder: all
  1.90.0-a.m+25.10.29.17.15:
    folder: all
