versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.15.17.36:
    folder: all
  1.90.0-a.d+25.10.20.16.37:
    folder: all
  1.90.0-a.d+25.10.22.11.59:
    folder: all
  1.90.0-a.d+25.10.23.22.37:
    folder: all
  1.90.0-a.d+25.10.25.00.41:
    folder: all
  1.90.0-a.d+25.10.27.15.18:
    folder: all
  1.90.0-a.d+25.10.30.14.49:
    folder: all
  1.90.0-a.d+25.11.03.14.53:
    folder: all
  1.90.0-a.m+25.07.08.21.07:
    folder: all
  1.90.0-a.m+25.10.27.11.03:
    folder: all
  1.90.0-a.m+25.11.03.10.34:
    folder: all
  1.90.0-b.1:
    folder: all
