versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.01.07.50:
    folder: all
  1.90.0-a.d+25.10.24.08.40:
    folder: all
  1.90.0-a.d+25.10.29.19.18:
    folder: all
  1.90.0-a.d+25.11.12.11.25:
    folder: all
  1.90.0-a.m+25.07.03.08.55:
    folder: all
  1.90.0-a.m+25.10.23.18.31:
    folder: all
  1.90.0-a.m+25.10.30.11.48:
    folder: all
