versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.01.17.19:
    folder: all
  1.90.0-a.d+25.10.19.19.15:
    folder: all
  1.90.0-a.d+25.10.21.19.06:
    folder: all
  1.90.0-a.d+25.10.23.21.53:
    folder: all
  1.90.0-a.d+25.11.04.19.07:
    folder: all
  1.90.0-a.d+25.11.06.23.10:
    folder: all
  1.90.0-a.m+25.10.01.17.19:
    folder: all
  1.90.0-a.m+25.10.21.19.06:
    folder: all
  1.90.0-a.m+25.10.23.21.53:
    folder: all
  1.90.0-a.m+25.11.04.19.07:
    folder: all
