versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.14.11.58:
    folder: all
  1.90.0-a.d+25.10.18.15.18:
    folder: all
  1.90.0-a.m+25.10.07.20.25:
    folder: all
  1.90.0-a.m+25.10.18.15.18:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.18.15.18:
    folder: all
  1.91.0-a.d+25.12.23.20.23:
    folder: all
  1.91.0-a.d+25.12.24.20.19:
    folder: all
  1.91.0-a.d+26.01.04.22.00:
    folder: all
  1.91.0-a.m+25.10.18.15.18:
    folder: all
