versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.03.18.32:
    folder: all
  1.90.0-a.d+25.10.23.15.24:
    folder: all
  1.90.0-a.d+25.10.30.12.54:
    folder: all
  1.90.0-a.d+25.11.03.10.17:
    folder: all
  1.90.0-a.d+25.12.15.13.39:
    folder: all
  1.90.0-a.d+25.12.18.11.52:
    folder: all
  1.90.0-a.m+25.10.15.18.57:
    folder: all
  1.90.0-a.m+25.10.24.06.31:
    folder: all
  1.90.0-a.m+25.10.30.16.18:
    folder: all
  1.90.0-a.m+25.12.15.15.13:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.18.11.52:
    folder: all
  1.91.0-a.m+25.12.15.15.13:
    folder: all
