versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.15.17.59:
    folder: all
  1.90.0-a.d+25.10.18.08.27:
    folder: all
  1.90.0-a.d+25.10.19.00.47:
    folder: all
  1.90.0-a.d+25.10.19.23.46:
    folder: all
  1.90.0-a.d+25.10.27.20.58:
    folder: all
  1.90.0-a.d+25.10.28.01.21:
    folder: all
  1.90.0-a.d+25.11.05.01.27:
    folder: all
  1.90.0-a.m+24.09.02.18.57:
    folder: all
  1.90.0-a.m+25.10.27.22.31:
    folder: all
  1.90.0-a.m+25.10.28.01.21:
    folder: all
  1.90.0-a.m+25.11.05.01.27:
    folder: all
  1.90.0-a.m+25.11.05.01.56:
    folder: all
  1.90.0-b.1:
    folder: all
