versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.02.08.37:
    folder: all
  1.90.0-a.d+25.10.27.17.10:
    folder: all
  1.90.0-a.d+25.10.29.08.50:
    folder: all
  1.90.0-a.m+25.02.24.11.42:
    folder: all
  1.90.0-a.m+25.10.27.21.21:
    folder: all
  1.90.0-a.m+25.10.29.12.09:
    folder: all
  1.90.0-b.1:
    folder: all
