versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.09.18.32:
    folder: all
  1.90.0-a.d+25.10.22.11.09:
    folder: all
  1.90.0-a.d+25.10.30.10.46:
    folder: all
  1.90.0-a.d+25.11.01.14.12:
    folder: all
  1.90.0-a.d+25.11.03.10.57:
    folder: all
  1.90.0-a.d+25.11.03.13.55:
    folder: all
  1.90.0-a.d+25.12.15.15.52:
    folder: all
  1.90.0-a.m+25.10.09.18.32:
    folder: all
  1.90.0-a.m+25.10.21.18.51:
    folder: all
  1.90.0-a.m+25.10.22.11.09:
    folder: all
  1.90.0-a.m+25.10.30.10.46:
    folder: all
  1.90.0-a.m+25.11.01.14.12:
    folder: all
  1.90.0-a.m+25.11.03.13.55:
    folder: all
  1.90.0-a.m+25.12.15.15.52:
    folder: all
  1.90.0-b.1:
    folder: all
