versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.13.12.35:
    folder: all
  1.90.0-a.d+25.11.23.23.11:
    folder: all
  1.90.0-a.d+25.11.28.15.18:
    folder: all
  1.90.0-a.d+25.11.30.22.46:
    folder: all
  1.90.0-a.d+25.12.15.00.35:
    folder: all
  1.90.0-a.d+25.12.15.13.13:
    folder: all
  1.90.0-a.d+25.12.16.19.56:
    folder: all
  1.90.0-a.m+25.10.13.12.35:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.16.19.56:
    folder: all
  1.91.0-a.d+25.12.23.23.20:
    folder: all
  1.91.0-a.m+25.10.13.12.35:
    folder: all
  1.91.0-a.m+25.12.23.17.31:
    folder: all
