versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.08.25.19.05:
    folder: all
  1.90.0-a.d+25.10.18.16.06:
    folder: all
  1.90.0-a.d+25.10.20.06.11:
    folder: all
  1.90.0-a.d+25.10.20.20.43:
    folder: all
  1.90.0-a.d+25.10.22.10.34:
    folder: all
  1.90.0-a.d+25.10.24.11.36:
    folder: all
  1.90.0-a.d+25.10.25.14.55:
    folder: all
  1.90.0-a.d+25.10.27.02.24:
    folder: all
  1.90.0-a.d+25.12.08.14.18:
    folder: all
  1.90.0-a.d+25.12.13.20.35:
    folder: all
  1.90.0-a.d+25.12.14.22.45:
    folder: all
  1.90.0-a.m+25.08.25.19.05:
    folder: all
  1.90.0-a.m+25.10.19.22.14:
    folder: all
  1.90.0-a.m+25.10.20.06.11:
    folder: all
  1.90.0-a.m+25.10.20.20.43:
    folder: all
  1.90.0-a.m+25.10.22.10.34:
    folder: all
  1.90.0-a.m+25.10.24.02.59:
    folder: all
  1.90.0-a.m+25.10.24.11.36:
    folder: all
  1.90.0-a.m+25.10.25.14.55:
    folder: all
  1.90.0-a.m+25.10.27.02.24:
    folder: all
  1.90.0-a.m+25.12.08.14.18:
    folder: all
  1.90.0-a.m+25.12.13.20.35:
    folder: all
  1.90.0-a.m+25.12.14.22.45:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.14.22.45:
    folder: all
  1.91.0-a.d+25.12.21.20.13:
    folder: all
  1.91.0-a.d+25.12.25.16.31:
    folder: all
  1.91.0-a.m+25.12.14.22.45:
    folder: all
  1.91.0-a.m+25.12.21.20.13:
    folder: all
