versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.09.20.09:
    folder: all
  1.90.0-a.d+25.11.06.21.06:
    folder: all
  1.90.0-a.d+25.12.16.21.35:
    folder: all
  1.90.0-a.d+25.12.17.17.35:
    folder: all
  1.90.0-a.m+25.10.09.20.09:
    folder: all
  1.90.0-a.m+25.12.16.21.35:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.17.17.35:
    folder: all
  1.91.0-a.d+25.12.22.18.46:
    folder: all
  1.91.0-a.d+26.01.01.01.01:
    folder: all
  1.91.0-a.d+26.01.08.19.21:
    folder: all
  1.91.0-a.m+25.12.16.21.35:
    folder: all
  1.91.0-a.m+26.01.08.19.21:
    folder: all
