versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.14.13.57:
    folder: all
  1.90.0-a.d+25.10.23.14.15:
    folder: all
  1.90.0-a.d+25.10.29.17.26:
    folder: all
  1.90.0-a.m+25.08.06.14.08:
    folder: all
  1.90.0-a.m+25.10.29.19.17:
    folder: all
