versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.19.09.06:
    folder: all
  1.90.0-a.d+25.10.27.09.17:
    folder: all
  1.90.0-a.d+25.11.05.20.16:
    folder: all
  1.90.0-a.d+25.11.07.18.37:
    folder: all
  1.90.0-a.m+25.09.20.17.53:
    folder: all
  1.90.0-b.1:
    folder: all
