versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.09.16.54:
    folder: all
  1.90.0-a.d+25.11.26.07.18:
    folder: all
  1.90.0-a.d+25.12.01.07.18:
    folder: all
  1.90.0-a.m+25.02.15.20.07:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.01.07.18:
    folder: all
  1.91.0-a.m+25.02.15.20.07:
    folder: all
