versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.06.18.38:
    folder: all
  1.90.0-a.d+25.10.28.17.40:
    folder: all
  1.90.0-a.m+25.09.14.14.59:
    folder: all
  1.90.0-a.m+25.10.06.18.38:
    folder: all
  1.90.0-a.m+25.10.28.17.40:
    folder: all
  1.90.0-b.1:
    folder: all
