versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.17.10.18:
    folder: all
  1.90.0-a.d+25.10.22.16.03:
    folder: all
  1.90.0-a.d+25.11.14.14.32:
    folder: all
  1.90.0-a.d+25.11.14.23.07:
    folder: all
  1.90.0-a.d+25.12.11.15.49:
    folder: all
  1.90.0-a.d+25.12.15.19.39:
    folder: all
  1.90.0-a.m+25.08.17.10.18:
    folder: all
  1.90.0-a.m+25.10.22.16.03:
    folder: all
  1.90.0-a.m+25.11.14.14.32:
    folder: all
  1.90.0-b.1:
    folder: all
