versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.04.15.18.33:
    folder: all
  1.90.0-a.m+25.04.15.18.33:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.04.15.18.33:
    folder: all
  1.91.0-a.d+25.12.26.19.43:
    folder: all
  1.91.0-a.d+26.01.06.18.03:
    folder: all
  1.91.0-a.m+25.04.15.18.33:
    folder: all
  1.91.0-a.m+26.01.06.18.03:
    folder: all
