versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.06.26.09.08:
    folder: all
  1.90.0-a.m+24.01.23.04.57:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.06.26.09.08:
    folder: all
  1.91.0-a.m+24.01.23.04.57:
    folder: all
