versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.08.06.22.32:
    folder: all
  1.90.0-a.d+25.10.30.08.28:
    folder: all
  1.90.0-a.d+25.10.30.20.41:
    folder: all
  1.90.0-a.d+25.11.05.21.42:
    folder: all
  1.90.0-a.d+25.11.05.23.25:
    folder: all
  1.90.0-a.d+25.12.01.22.49:
    folder: all
  1.90.0-a.d+25.12.04.00.07:
    folder: all
  1.90.0-a.m+25.08.06.22.37:
    folder: all
  1.90.0-a.m+25.10.30.22.12:
    folder: all
  1.90.0-a.m+25.11.05.23.27:
    folder: all
  1.90.0-a.m+25.12.04.00.07:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.04.00.07:
    folder: all
  1.91.0-a.m+25.12.04.00.07:
    folder: all
