versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.08.06.22.32:
    folder: all
  1.90.0-a.d+25.10.30.08.28:
    folder: all
  1.90.0-a.m+25.08.06.22.37:
    folder: all
