versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.16.09.15:
    folder: all
  1.90.0-a.d+25.12.11.22.17:
    folder: all
  1.90.0-a.m+25.10.11.17.36:
    folder: all
  1.90.0-a.m+25.10.16.09.15:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.11.22.17:
    folder: all
  1.91.0-a.d+25.12.23.20.25:
    folder: all
  1.91.0-a.d+25.12.24.20.21:
    folder: all
  1.91.0-a.d+26.01.04.11.10:
    folder: all
  1.91.0-a.m+25.10.16.09.15:
    folder: all
  1.91.0-a.m+25.12.23.20.25:
    folder: all
  1.91.0-a.m+25.12.26.22.05:
    folder: all
