versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.06.28.11.15:
    folder: all
  1.90.0-a.m+24.12.28.17.19:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.06.28.11.15:
    folder: all
  1.91.0-a.m+24.12.28.17.19:
    folder: all
