versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.15.01.40:
    folder: all
  1.90.0-a.d+25.10.18.17.53:
    folder: all
  1.90.0-a.d+25.10.20.09.04:
    folder: all
  1.90.0-a.d+25.10.21.20.47:
    folder: all
  1.90.0-a.m+25.10.12.13.14:
    folder: all
  1.90.0-a.m+25.10.18.17.53:
    folder: all
  1.90.0-a.m+25.10.20.09.04:
    folder: all
  1.90.0-a.m+25.10.21.20.47:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.10.21.20.47:
    folder: all
  1.91.0-a.d+26.01.05.13.15:
    folder: all
  1.91.0-a.m+25.10.21.20.47:
    folder: all
