versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.06.20.36:
    folder: all
  1.90.0-a.d+25.11.29.09.14:
    folder: all
  1.90.0-a.d+25.11.30.08.56:
    folder: all
  1.90.0-a.m+25.09.17.08.31:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.11.30.08.56:
    folder: all
  1.91.0-a.m+25.09.17.08.31:
    folder: all
