versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.10.03.12.26:
    folder: all
  1.90.0-a.d+25.10.08.16.46:
    folder: all
  1.90.0-a.d+25.10.22.19.18:
    folder: all
  1.90.0-a.d+25.11.05.11.30:
    folder: all
  1.90.0-a.d+25.11.14.12.03:
    folder: all
  1.90.0-a.d+25.12.15.18.23:
    folder: all
  1.90.0-a.m+23.12.22.17.12:
    folder: all
  1.90.0-a.m+25.10.03.12.26:
    folder: all
  1.90.0-a.m+25.11.14.12.03:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.15.18.23:
    folder: all
  1.91.0-a.m+25.11.14.12.03:
    folder: all
