versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.09.29.17.22:
    folder: all
  1.90.0-a.d+25.10.21.18.52:
    folder: all
  1.90.0-a.d+25.10.24.12.28:
    folder: all
  1.90.0-a.d+25.10.24.18.01:
    folder: all
  1.90.0-a.d+25.10.24.20.29:
    folder: all
  1.90.0-a.d+25.10.31.11.15:
    folder: all
  1.90.0-a.m+25.09.29.17.22:
    folder: all
  1.90.0-a.m+25.10.21.18.52:
    folder: all
  1.90.0-a.m+25.10.24.18.01:
    folder: all
