versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.01.22.11.25:
    folder: all
  1.90.0-a.d+25.03.31.23.33:
    folder: all
  1.90.0-a.d+25.06.06.11.27:
    folder: all
  1.90.0-a.d+25.10.24.06.40:
    folder: all
  1.90.0-a.d+25.12.02.08.38:
    folder: all
  1.90.0-a.m+25.03.10.14.19:
    folder: all
  1.90.0-a.m+25.06.06.11.27:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.02.08.38:
    folder: all
  1.91.0-a.m+25.06.06.11.27:
    folder: all
