versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.09.13.13.52:
    folder: all
  1.90.0-a.m+25.09.13.13.52:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.09.13.13.52:
    folder: all
  1.91.0-a.d+25.12.24.20.23:
    folder: all
  1.91.0-a.d+26.01.04.11.27:
    folder: all
  1.91.0-a.m+25.09.13.13.52:
    folder: all
  1.91.0-a.m+25.12.29.12.31:
    folder: all
