versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.06.15.17.50:
    folder: all
  1.90.0-a.d+25.10.01.17.38:
    folder: all
  1.90.0-a.d+25.12.13.20.40:
    folder: all
  1.90.0-a.d+25.12.14.15.29:
    folder: all
  1.90.0-a.m+25.06.15.17.50:
    folder: all
  1.90.0-a.m+25.10.01.17.38:
    folder: all
  1.90.0-a.m+25.12.13.20.40:
    folder: all
  1.90.0-a.m+25.12.14.15.29:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.12.14.15.29:
    folder: all
  1.91.0-a.m+25.12.14.15.29:
    folder: all
