versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.08.27.11.08:
    folder: all
  1.90.0-a.d+25.11.19.14.34:
    folder: all
  1.90.0-a.d+25.11.26.12.51:
    folder: all
  1.90.0-a.d+25.12.05.19.45:
    folder: all
  1.90.0-a.m+24.07.07.14.32:
    folder: all
  1.90.0-a.m+25.11.19.14.34:
    folder: all
  1.90.0-a.m+25.12.11.15.20:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.11.19.14.34:
    folder: all
  1.91.0-a.m+25.12.11.15.20:
    folder: all
