versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.05.02.19.05:
    folder: all
  1.90.0-a.m+22.09.12.08.08:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.05.02.19.05:
    folder: all
  1.91.0-a.m+22.09.12.08.08:
    folder: all
