versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0:
    folder: all
  1.90.0-a.d+25.07.02.16.58:
    folder: all
  1.90.0-a.m+24.12.28.21.57:
    folder: all
  1.90.0-b.1:
    folder: all
  1.91.0-a.d+25.07.02.16.58:
    folder: all
  1.91.0-a.m+24.12.28.21.57:
    folder: all
