versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.07.16.56:
    folder: all
  1.90.0-a.m+25.06.07.13.20:
    folder: all
  1.90.0-a.m+25.10.07.16.56:
    folder: all
  1.90.0-b.1:
    folder: all
