versions:
  1.89.0:
    folder: all
  1.89.0-b.1:
    folder: all
  1.90.0-a.d+25.10.09.08.54:
    folder: all
  1.90.0-a.d+25.10.22.16.51:
    folder: all
  1.90.0-a.d+25.10.29.12.01:
    folder: all
  1.90.0-a.d+25.11.05.18.20:
    folder: all
  1.90.0-a.d+25.11.13.19.36:
    folder: all
  1.90.0-a.m+25.07.29.12.30:
    folder: all
  1.90.0-a.m+25.10.29.12.01:
    folder: all
  1.90.0-a.m+25.11.13.19.36:
    folder: all
  1.90.0-b.1:
    folder: all
